#' BAS tag data processing
#'
#' Basic data processing for British Antarctic Survey archival tags.
#' Provides facilities for importing and plotting data recorded by the
#' BAS tags, and in particular detecting times of twilight from the
#' recorded light data.
#'
#' @name BAStag-package
#' @docType package
#' @author Simon Wotherspoon, Micheal Sumner and Simeon Lisovski.
NULL



## Data import


##' Read light data from a BAS tag
##'
##' The \code{read.lig} imports the light record from a ".lig" file
##' generated by a BAS tag.
##' @title Read Light Data
##' @param file the light file to import.
##' @return Returns a dataframe with columns
##' \item{\code{Valid}}{an indicator of whether the record is valid}
##' \item{\code{Date}}{the date and time of the observation}
##' \item{\code{Julian}}{date and time as Julian date}
##' \item{\code{Light}}{the recorded light level}
##' @export
read.lig <- function(file) {
  ## Read csv file and add column names
  d <- read.csv(file,header=F,
                col.names=c("Valid","Date","Julian","Light"),
                colClasses=c("character","character","numeric","integer"))
  ## Parse date
  d$Date <- as.POSIXct(strptime(d$Date,"%d/%m/%y %H:%M:%S",tz="GMT"))
  d
}



##' Read the activity data from a BAS tag
##'
##' The \code{read.act} imports the light record from a ".act" file
##' generated by a BAS tag.
##'
##' @title Read Activity Data
##' @param file the activity file to import.
##' @return Returns a dataframe with columns
##' \item{\code{Valid}}{an indicator of whether the record is valid}
##' \item{\code{Date}}{the date and time of the observation}
##' \item{\code{Julian}}{date and time as Julian date}
##' \item{\code{Activity}}{the recorded activity level}
##' \item{\code{SST}}{the recorded sea surface temperature}
##' @export
read.act <- function(file) {
  ## Read csv file and add column names.  Must explicitly specify
  ## column names as R cannot detect the correct number of columns to
  ## read
  d <- read.csv(file,header=F,
                col.names=c("Valid","Date","Julian","Activity","SST"))
  ## Parse date
  d$Date <- as.POSIXct(strptime(d$Date,"%d/%m/%y %H:%M:%S",tz="GMT"))
  ## Add day number and time within day (as fraction of a day)
  d$Day <- floor(d$Julian)
  d$Time <- d$Julian-d$Day
  d
}



##' Utilities for manipulating hours
##'
##' Given a vector of POSIXct dates, \code{as.hour} extracts the time
##' of day component of the date and returns it as decimal hours.
##' Given a vector of decimal hours, \code{hour.offset} recodes the
##' decimal hour into a new 24 hour interval.
##' @title Hour Manipulation
##' @rdname hours
##' @param tm them timestamp as POSIXct.
##' @param hr the decimal hour to be wrap.
##' @param offset minimum hour of the interval to wrap into.
##' @return Return a decimal hour.
##' @examples
##' as.hour(as.POSIXct("2005-11-12 19:58:00"))
##' hour.offset(1:10,5)
##' @export
as.hour <- function(tm) {
  (as.numeric(tm)-as.numeric(as.POSIXct(as.Date(tm))))/3600
}


##' @rdname hours
##' @export
hour.offset <-  function(hr,offset=0) {
  (hr-offset)%%24+offset
}


##' Display time series data as an image.
##'
##' The \code{tsimage} function divides a regular sequence of samples
##' into 24 hour periods, packs these into the columns of a matrix and
##' displays the result as an image.
##'
##' The \code{tsimage.locator} function allows the user to select
##' pixels with the mouse pointer in the style of \code{locator}, and
##' returns the times corresponding to the selected pixels.
##'
##' These functions ignore clock drift and assume the sampling period
##' exactly divides 24 hours.
##'
##' @title Display Tag Data as an Image
##' @param date the sequence of sample times as POSIXct.
##' @param y the sequence of responses.
##' @param offset the starting hour for the vertical axis.
##' @param xlab the x axis label.
##' @param ylab the y axis label.
##' @param ... additional arguments to be passed to \code{image}.
##' @param im the axes coordinates returned by \code{tsimage}.
##' @param n the number of points to select.
##' @return
##' \code{tsimage} returns the date and hour coordinates of the image
##' grid.
##' \code{tsimage.locator} returns the times corresponding to the
##' selected pixels.
##' @export
tsimage <- function(date,y,offset=0,xlab="Date",ylab="Hour",...) {

  ## Estimate sampling interval rounded to nearest minute
  dt <- 60*round(median(diff(as.numeric(date)))/60)
  ## Calculate number of rows m, number of columns n, and number of
  ## pixels to pad at front
  m <- 24*60*60/dt
  pad <- floor(((as.hour(date[1])-offset)%%24)*60*60/dt)
  n <- ceiling((length(y)+pad)/m)
  ## Hour of each row (strictly increasing)
  hour <- as.hour(seq(date[1]-pad*dt,by=dt,length=m))
  hour <- hour[1]+cumsum(c(0,diff(hour)%%24))
  ## Date of first pixel in each column.
  day <- seq(date[1]-pad*dt,by=m*dt,length=n+1)
  y <- matrix(c(rep(NA,pad),y,rep(NA,m*n-pad-length(y))),m,n)
  ## Show as image, with hours wrapped to [0,24].
  image(day,hour,t(y),axes=F,xlab=xlab,ylab=ylab,...)
  axis.POSIXct(1,day)
  axis(2,at=seq(0,48,by=4),labels=seq(0,48,by=4)%%24)
  box()
  invisible(list(date=day,hour=hour,offset=hour[1]-dt/2))
}

##' @rdname tsimage
##' @export
tsimage.locator <- function(im,n=512) {
  ## Force evaluation of im.
  im <- im
  ## Select pixels and convert to date/time.
  loc <- locator(n)
  im$date[.bincode(loc$x,as.numeric(im$date),right=F)]+3600*(loc$y-min(im$hour))
}


##' Plot times as hour vs date
##'
##' Analogs of \code{plot}, \code{points} and \code{lines} that plot
##' the time of day against date.  The \code{tsimage.ribbon} uses
##' \code{polygon} to produce a polygonal "ribbon" that represents a
##' series of daily time intervals.
##'
##' @title tsimage plot
##' @param date times as a vector of POSIXct.
##' @param date1 lower bound as a vector of POSIXct.
##' @param date2 upper bound as a vector of POSIXct.
##' @param offset the starting hour for the vertical axes.
##' @param xlab the label for the x axis.
##' @param ylab the label for the y axis.
##' @param ... additional arguments parameters to pass to \code{plot},
##' \code{points} or \code{lines}.
##' @export
tsimage.plot <- function(date,offset,xlab="Date",ylab="Hour",...) {
  plot(date,hour.offset(as.hour(date),offset%%24),xlab=xlab,ylab=ylab,...)
}

##' @rdname tsimage.plot
##' @export
tsimage.points <- function(date,offset,...) {
  points(date,hour.offset(as.hour(date),offset%%24),...)
}

##' @rdname tsimage.plot
##' @export
tsimage.lines <- function(date,offset,...) {
  lines(date,hour.offset(as.hour(date),offset%%24),...)
}

##' @rdname tsimage.plot
##' @export
tsimage.ribbon <- function(date1,date2,offset,...) {
  hour1 <- hour.offset(as.hour(date1),offset)
  hour2 <- hour.offset(as.hour(date2),offset)
  hour2 <- ifelse(hour1 < hour2,hour2,hour2+24)
  xs <- c(date1,rev(date2))
  ys <- c(hour1,rev(hour2))
  polygon(xs,ys-24,...)
  polygon(xs,ys,...)
  polygon(xs,ys+24,...)
}



##' Display light series as an image.
##'
##' The \code{light.image} function displays sequence of light
##' samples into 24 hour periods, packs these into the columns of a
##' matrix and displays the result as an image.
##'
##' This function is essentially a wrapper for \code{tsimage}.
##' @title Display Light Data as an Image
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param offset the offset for the vertical axis in hours.
##' @param zmax the maximum light level.
##' @param xlab the x axis label.
##' @param ylab the y axis label.
##' @param ...  additional arguments to pass to image.
##' @return Returns the date and hour coordinates of the image grid.
##' @export
light.image <- function(tagdata,offset=0,zmax=64,xlab="Date",ylab="Hour",...) {

  tsimage(tagdata$Date,tagdata$Light,offset,
          zlim=c(0,zmax),col=grey(seq(0,1,length=64)),
          xlab=xlab,ylab=ylab,...)
}


##' Search for pairs of twilights spanning night.
##'
##' Search for sunset, sunrise pairs that correspond to a given light
##' threshold.
##'
##' Given a set of times (\code{include}) known to fall in the night,
##' \code{find.twilights} determines the twilights that span these times, and
##' computes the corresponding midnights. It then searches for periods
##' of darkness that lie approximately 24 hours from these midnights,
##' repeating the process until no new twilight pairs are found.
##'
##' If \code{interleave=TRUE}, the sunrise and sunset times are
##' interleaved andreturned as a single sequence of twilights,
##' otherwise sunset and sunrise times are returned separately. The
##' function \code{interleave.twilights} takes a dataframe of separate
##' sunset and sunrise times and interleaves them to form a sequence
##' of twilight times.
##'
##' @title Search for twilight times
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param threshold the light threshold that defines twilight.
##' @param include a vector of times as POSIXct. Nights that span these
##' times are included in the search.
##' @param exclude a vector of POSIXct times. Nights that span these
##' times are excluded from the search.
##' @param extend a time in minutes. The function seeks periods of
##' darkness that differ from one another by 24 hours plus or minus
##' this interval.
##' @param dark.min a time in minutes. Periods of darkness shorter
##' than this interval will be excluded.
##' @return A dataframe with columns
##' \item{\code{Twilight}}{times of twilight}
##' \item{\code{Rise}}{logical indicating sunrise}
##' where each row corresponds to a single twilight.
##' @export
find.twilights <- function(tagdata,threshold,include,
                           exclude=NULL,extend=0,dark.min=0) {
  ## Extract date and light data
  date <- tagdata$Date
  light <- tagdata$Light


  ## Is any x in each [a,b]
  contains.any <- function(a,b,x) {
    f <- logical(length(a))
    for(k in seq_along(x))
      f <- f | (a <= x[k] & b >= x[k])
    f
  }

  ## Convert to minutes
  extend <- 60*extend
  dark.min <- 60*dark.min

  ## Calculate intervals [a,b] of darkness
  ## a is first points before light drops below threshold
  ## b is first points before light rises to or above threshold
  l <- (light>=threshold)
  f <- diff(l)
  a <- which(f==-1)
  b <- which(f==1)
  ## Keep only fall-rise pairs
  if(b[1] < a[1]) b <- b[-1]
  a <- a[1:length(b)]

  ## Only keep intervals that do not include excluded data and are
  ## less than 24 hours in length
  keep <- (!contains.any(date[a],date[b+1],exclude) &
           (as.numeric(date[b+1])-as.numeric(date[a]) < 86400) &
           (as.numeric(date[b+1])-as.numeric(date[a]) > dark.min))

  a <- a[keep]
  b <- b[keep]

  ## Compute bounding dates and midpoint
  aDate <- date[a]
  bDate <- date[b+1]
  mDate <- aDate+(bDate-aDate)/2

  ## Iteratively expand set of twilights by searching for additional
  ## twilights +/- 24 hrs from midpoints of existing set.
  keep <- logical(length(a))
  add <- contains.any(aDate,bDate,include) & !keep
  while(any(add)) {
    keep <- keep | add
    mid <- c(mDate[add]-86400,mDate[add]+86400)
    add <- contains.any(aDate-extend,bDate+extend,mid) & !keep
  }
  a <- a[keep]
  b <- b[keep]

  ## Interpolate times to get exact twilights.
  ss <- date[a]+(threshold-light[a])/(light[a+1]-light[a])*(date[a+1]-date[a])
  sr <- date[b]+(threshold-light[b])/(light[b+1]-light[b])*(date[b+1]-date[b])


  data.frame(Twilight=.POSIXct(as.vector(t(cbind(ss,sr))),"GMT"),
             Rise=rep(c(F,T),length(ss)))
}





##' Search for crepuscular intervals
##'
##' Using the twilights calculated by \code{find.twilights},
##' \code{find.crepuscular} searchs for the intervals of reduced light
##' intensity around twilight and returns the dataframe constructed by
##' \code{find.twilights} augmented with the start and end times of
##' the crepuscular segment. The sugset of data corresponding to these
##' segments can be extracted with \code{extract.crepuscular}.
##'
##' @title Search for crepuscular light segments
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param twilights a dataframe generated by
##' \code{\link{find.twilights}}.
##' @param min.threshold the light level that defines the dark end of
##' the crepuscular period.
##' @param max.threshold the light level that defines the light end of
##' the crepuscular period.
##' @param extend.dark the number of hours to search towards midnight.
##' @param extend.light the number of hours to search towards noon.
##' @return A dataframe with columns.
##' \item{\code{Twilight}}{times of twilight}
##' \item{\code{Rise}}{logical indicating sunrise}
##' \item{\code{Start}}{the start of the crepuscular period}
##' \item{\code{End}}{the end of the crepuscular period}
##' where each row corresponds to a single twilight.
##' @export
find.crepuscular <- function(tagdata,twilights,
                             min.threshold=0,max.threshold=60,
                             extend.dark=1,extend.light=2) {

  runlength <- function(x) {
    y <- cumsum(x)
    y-cummax(ifelse(!x,y,0))
  }

  ## Extract date and light
  date <- tagdata$Date
  light <- tagdata$Light

  twilight <- twilights$Twilight
  rise <- twilights$Rise
  start <- twilight
  end <-twilight
  ks <- findInterval(twilight,date)

  ## Loop over twilights
  for(i in seq_along(twilight)) {
    if(rise[i]) {
      ## Search forward to noon
      k <- ks[i]
      ls <- light[date > date[k] & date <= date[k]+extend.light*60*60]
      end[i] <- date[k+min(which(ls >= max.threshold),length(ls))]
      ## Search backward to midnight
      k <- ks[i]+1
      ls <- light[date <= date[k] & date >= date[k]-extend.dark*60*60]
      rs <- rev(runlength(ls==0))
      start[i] <- date[k+1-min(which(rs>=min(max(rs),4)))]
    } else {
      ## Search backward to noon
      k <- ks[i]+1
      ls <- light[date < date[k] & date >= date[k]-extend.light*60*60]
      start[i] <- date[k-min(which(rev(ls) >= max.threshold),length(ls))]
      ## Search forward to midnight
      k <- ks[i]
      ls <- light[date >= date[k] & date <= date[k]+extend.dark*60*60]
      rs <- rev(runlength(rev(ls)==0))
      end[i] <- date[k-1+min(which(rs>=min(max(rs),4)))]
    }
  }

  data.frame(Twilight=twilight,
             Rise=rise,
             Start=start,
             End=end)
}




##' Extract crepuscular light segments
##'
##' Extract the crepuscular subsets of the light data, given a
##' dataframe of start and end points generated by
##' \code{\link{find.crepuscular}}.
##'
##' The \code{adjust.interval} argument can be used to specify a
##' timing adjustment for tags that report the maximum light level
##' observed in the preceeding sampling interval. If this argument is
##' zero, no adjustment is made, otherwise the timestamps of sunset
##' intervals will be adjusted by this interval to compensate for the
##' recording behaviour of the tag.
##'
##' If \code{filter.threshold} is non \code{NULL}, the light levels
##' are filtered to remove shaded observations.  The light levels at
##' sunrise and sunset are assumed to be monotonic increasing, and the
##' running mximum in the direction of day is calculated.  Light
##' levels that are \code{filter.threshold} units below the running
##' maximum are removed.
##'
##' @title Extract crepuscular light segments
##' @param tagdata a dataframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param twilights a dataframe generated by
##' \code{\link{find.crepuscular}}.
##' @param adjust.interval timing adjustment for sunset intervals.
##' @param filter.threshold \code{NULL} or a positive threshold.
##' @return Returns a dataframe with columns
##' \item{\code{Date}}{the date and time of the observation}
##' \item{\code{Light}}{the recorded light level}
##' \item{\code{Segment}}{an integer identifying the segment}
##' @export
extract.crepuscular <- function(tagdata,twilights,
                                adjust.interval=0,filter.threshold=NULL) {
  date <- vector(mode="list",nrow(twilights))
  lght <- vector(mode="list",nrow(twilights))
  sgmt <- vector(mode="list",nrow(twilights))
  indices <- as.numeric(factor(as.numeric(twilights$Twilight)))
  ## For each twilight
  for(k in seq_len(nrow(twilights))) {
    is <- which(tagdata$Date >= twilights$Start[k] &
                tagdata$Date <= twilights$End[k])
    ## Remove non-increasing segments
    if(!is.null(filter.threshold)) {
      light <- tagdata$Light[is]
      lower <- if(twilights$Rise[k]) cummax(light) else rev(cummax(rev(light)))
      is <- is[light >= lower-filter.threshold]
    }
    ## Timing offset
    off <- if(!twilights$Rise[k]) adjust.interval else 0
    date[[k]] <- tagdata$Date[is]-off
    lght[[k]] <- tagdata$Light[is]
    sgmt[[k]] <- rep(indices[k],length.out=length(is))
  }
  data.frame(Date=.POSIXct(unlist(date),"GMT"),
             Light=unlist(lght),
             Segment=unlist(sgmt))
}



##' Find intervals of darkness spanning more than 24 hours.
##'
##' The \code{\link{find.twilights}} function find twilight times by
##' searching for adjacent nights, but is unable to search beyond a
##' period of light or dark spaaning greater than 24 hours.  This function
##' finds extended periods of light or dark that span more than 24 hours.
##' @title Find extended periods of light or dark
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param threshold the light threshold that defines twilight.
##' @return A dataframe with one row for each intervals and columns
##' \item{\code{Start}}{the start of the interval as POSIXct}
##' \item{\code{Start}}{the end of the interval as POSIXct}
##' \item{\code{Midpoint}}{the midpoint of the interval as POSIXct}
##' @export
find.chunk24 <- function(tagdata,threshold) {

  ## Extract date and light data
  date <- tagdata$Date
  light <- tagdata$Light


  ## Calculate light/dark transitions
  l <- (light>=threshold)
  f <- diff(l)
  ab <- which(abs(f)==1)
  ab <- ab+f[ab]==1
  ## Find blocks longer than 24 hrs and return
  tm <- as.numeric(date[ab])
  keep <- which(diff(tm) >= 86400)
  a <- ab[keep]
  b <- ab[keep+1]
  data.frame(Start=date[a],
             End=date[b],
             Midpoint=date[a] + (date[b+1]-date[a])/2)
}







##' Adjust twilight estimates for BAS light recording.
##'
##' BAS tags record the maximum light level observd in the preceding
##' sampling interval, and this behaviour biases naive estimates of
##' the times of sunset.  This function offsets sunset times by the
##' sampling interval to correct for this bias.
##' @title Twilight Adjustment
##' @param twilights dataframe of twilight times.
##' @param interval the sampling interval.
##' @return a dataframe of bias correct twilight times.
##' @export
twilight.adjust <- function(twilights,interval) {
  twilights$Twilight[!twilights$Rise] <- twilights$Twilight[!twilights$Rise]-interval
  twilights
}



##' Calibrate threshold light level to solar zenith angle
##'
##' Given data for a known location, this plots the recorded light
##' against the solar zenith angle to allow observed light levels to
##' be calibrated to solar zenith angle.
##' @title Light Threshold Calibration
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param lon calibration longitude.
##' @param lat calibration latitude.
##' @param max.adjust adjust twilights for tags that report the
##' maximum light interval observed in the preceeding sampling
##' interval.
##' @param col colors for increasing and decreasing zenith angles
##' @param ... additional arguments to pass to \code{plot}.
##' @export
threshold.calibrate <- function(tagdata,lon,lat,max.adjust=TRUE,
                                col=c("dodgerblue","firebrick"),...) {
  Light <- tagdata$Light
  Zenith <- zenith(solar(tagdata$Date),lon,lat)
  if(max.adjust) {
    n <- length(Light)
    Light <- Light[-1]
    Zenith <- pmin(Zenith[-1],Zenith[-n])
  }
  n <- length(Zenith)
  dz <- Zenith[c(2:n,n)] - Zenith[c(1,1:(n-1))]
  plot(Zenith,Light,col=ifelse(dz > 0,col[1],col[2]),...)
}


##' Adjust time for clock drift
##'
##' Linearly rescale a sequence of dates to a new start and end time
##' to correct for clock drift in the tag.
##' @title Clock Drift Adjustment
##' @param time a vector of POSIXct times.
##' @param start new start time as POSIXct.
##' @param end new end time as POSIXct.
##' @export
drift.adjust <- function(time,start,end) {
  n <- length(time)
  .POSIXct(approx(time[c(1,n)],c(start,end),time)$y)
}



##' Interactively edit twilight times
##'
##' Interactively edit times of twilight based on the light profile.
##' A plot of the estimated sunrise and sunset intervals is displayed,
##' and the user can select the twilight to be edited with a left
##' mouse click.
##'
##' The light profile for the selected twilight is shown in a separate
##' window, and the selected time of twilight is highlighted.  The
##' corresponding light profiles from the preceeding and following
##' days are also shown for reference.
##'
##' The user may select a new candidate twilight by left clicking with
##' the mouse, or the twilight can marked for deletion with the right
##' mouse button.
##'
##' Note however, no actual change to the selection is made until the
##' candidate edits are accepted depressing the 'a' key.
##'
##' Each twilight may be marked with the an integer 0 to 9 with the
##' numeric keys. By default each day is given the mark 0.
##'
##' In either window
##' \tabular{ll}{
##' 'q' \tab Quits, returning the dataframe of edited twilight segments \cr
##' 'a' \tab Accepts the candidate edit \cr
##' 'x' \tab Resets the selection \cr
##' 'p' \tab Toggles the display of individual points \cr
##' '+'/'-' \tab Zoom in or out \cr
##' 'Left arrow' \tab Jump to previous twilight \cr
##' 'Right arrow' \tab Jump to ext twilight \cr
##' '0'-'9' \tab Mark this twilight \cr
##' }
##'
##' @title Edit twilights
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param twilights dataframe of twilight times as generated by
##' \code{\link{find.twilights}}.
##' @param offset the starting hour for the vertical axes.
##' @param extend the period (in hours) before and after twilight for
##' which the light profile should be plotted.
##' @param threshold the light threshold that defines twilight.
##' @param ymax the maximum light level to plot.
##' @param twilight.col the colors of the estimated sunrise and sunset times.
##' @param light.col the colors of the light profiles for the day
##' before, the selected twilight and the day after.
##' @param threshold.col the colors of the threshold markers.
##' @param point.cex expansion factor for plot points.
##' @param width width of the interface windows.
##' @param height height of the interface windows.
##' @seealso \code{\link{crepuscular.editW}}
##' @return the dataframe of edited twilights, with columns
##' \item{\code{Twilight}}{edited times of twilight}
##' \item{\code{Rise}}{logical indicating sunrise}
##' \item{\code{Original}}{original times of twilight}
##' @export
twilight.editW <- function(tagdata,twilights,offset=0,extend=6,threshold=NULL,ymax=64,
                           twilight.col=c("dodgerblue","firebrick","grey80"),
                           light.col=c("#CCFFCC","black","#CCCCFF"),
                           threshold.col=c("red","grey95"),point.cex=0.5,width=10,height=5) {

  ## Extract date and light
  date <- tagdata$Date
  light <- tagdata$Light
  ## Order twilights and check deleted
  twilights <- twilights[order(twilights$Twilight),]
  if(is.null(twilights$Deleted)) twilights$Deleted <- logical(nrow(twilights))
  if(is.null(twilights$Marker)) twilights$Marker <- integer(nrow(twilights))
  ## Extract date and hour of twilight
  day <- twilights$Twilight
  hour <- hour.offset(as.hour(twilights$Twilight),offset)

  ## Record original times
  twilights$TwilightOriginal <- twilights$Twilight

  ## Cached data subsets
  index <- 1
  twl <- twilights$Twilight[index]
  marker <- twilights$Marker[index]
  deleted <- twilights$Deleted[index]
  twls <- NULL
  edit.pt <- NULL
  dteA <- dteB <- dteC <- NULL
  lgtA <- lgtB <- lgtC <- NULL

  changed <- FALSE
  show.obs <- FALSE

  ## Set cached values
  cache <- function(k) {
    index <<- k
    twl <<- twilights$Twilight[index]
    deleted <<- twilights$Deleted[index]
    marker <<- twilights$Marker[index]
    keep <- (twilights$Twilight >= twl-3600*extend) & (twilights$Twilight <= twl+3600*extend)
    keep[index] <- FALSE
    twls <<- twilights$Twilight[keep]
    edit.pt <<- NULL
    changed <<- FALSE
    ## Get profiles
    keep <- (date >= twl-86400-3600*extend) & (date <= twl-86400+3600*extend)
    dteA <<- date[keep]
    lgtA <<- light[keep]
    keep <- (date >= twl - 3600*extend) & (date <= twl + 3600*extend)
    dteB <<- date[keep]
    lgtB <<- light[keep]
    keep <- (date >= twl+86400-3600*extend) & (date <= twl+86400+3600*extend)
    dteC <<- date[keep]
    lgtC <<- light[keep]
  }

  ## Select device
  devset <- function(dev) {
    if(dev.cur()!=dev) dev.set(dev)
  }
  ## Focus if possible
  focus <- if(exists("bringToTop",mode="function")) bringToTop else devset

  ## Draw the twilights window
  twlght.draw <- function() {
    plot(day,hour,
         pch=16,cex=point.cex,
         xlab="Date",ylab="Hour",
         ylim=c(offset,offset+24),
         col=twilight.col[ifelse(twilights$Deleted,3,ifelse(twilights$Rise,1,2))])
    points(day[index],hour[index],pch=3)
  }

  ## Draw light profiles
  profile.draw <- function() {
    ## Draw axes for light profiles
    mlab <- if(marker>0) paste("Marker: ",marker) else ""
    plot(dteB,lgtB,xlab=mlab,ylab="Light",type="n",xaxt="n",main=as.character(twl))
    axis.POSIXct(1,x=dteB,format="%H:%M")
    ## Overlay with light threshold
    if(!is.null(threshold))
      abline(h=threshold,col=threshold.col)
    ## Overlay the light profile for the selected and surrounding days
    lines(dteA+86400,lgtA,col=light.col[1])
    lines(dteC-86400,lgtC,col=light.col[3])
    lines(dteB,lgtB,col=light.col[2])
    if(show.obs) points(dteB,lgtB,col=light.col[2],pch=16,cex=point.cex)
    abline(v=twls,col=threshold.col[2])
    abline(v=twl,col=if(!deleted) threshold.col[1] else light.col[2])
    if(changed) points(edit.pt[1],edit.pt[2],pch=16,col=threshold.col[1])
  }


  ## onMouseDown callback for twilights window.
  twlOnMouseDown <- function(buttons,x,y) {
    ## Determine selected profile.
    devset(twlght.dev)
    x <- grconvertX(x,from="ndc",to="user")
    y <- grconvertY(y,from="ndc",to="user")
    r <- ((x-as.numeric(day))/3600)^2+((y-hour+12)%%24-12)^2
    k <- which.min(r)
    ## Redraw
    cache(k)
    devset(twlght.dev)
    twlght.draw()
    devset(profile.dev)
    profile.draw()
    focus(profile.dev)
    NULL
  }

  ## onKeybd callback for both windows
  onKeybd <- function(key) {
    ## q quits
    if(key=="q") return(-1)
    ## +/- : zoom time window around threshold crossing
    if(key=="+") {
      extend <<- max(extend-1,1)
      cache(index)
    }
    if(key=="-") {
      extend <<- min(extend+1,24)
      cache(index)
    }
    ## x : reset selection
    if(key=="x") {
      cache(index)
    }
    ## p : toggle display of points in the profile window
    if(key=="p") {
      show.obs <<- (show.obs==FALSE)
      cache(index)
    }
    ## Left/Right : jump to neighbouring twilight
    if(key=="Left") {
      cache(max(index-1,1))
    }
    if(key=="Right") {
      cache(min(index+1,nrow(twilights)))
    }
    ## a : accept current edit
    if(key=="a") {
      twl <<- edit.pt[1]
      twilights$Twilight[index] <<- .POSIXct(twl,"GMT")
      edit.pt <<- NULL
      changed <<- FALSE
    }
    if(key >= "0" && key <= "9") {
      marker <<- as.numeric(key)
      twilights$Marker[index] <<- marker
    }

    ## Redraw
    devset(twlght.dev)
    twlght.draw()
    devset(profile.dev)
    profile.draw()
    NULL
  }

  ## onMouseDown callback for profile window
  prfOnMouseDown <- function(buttons,x,y) {
    ## Button 1 -> record location
    if(length(buttons) > 0 && buttons[1]==0) {
      changed <<- TRUE
      edit.pt <<- c(grconvertX(x,from="ndc",to="user"),
                    grconvertY(y,from="ndc",to="user"))
    }
    ## Button 2 -> toggle deletion
    if(length(buttons) > 0 && buttons[1]==2) {
      deleted <- (deleted==FALSE)
      twilights$Deleted[index] <<- deleted
      cache(index)
    }
    profile.draw()
    NULL
  }


  ## Set up twilights window
  index <- 1
  cache(index)
  X11(width=width,height=height)
  twlght.draw()
  twlght.dev <- dev.cur()
  focus(twlght.dev)
  setGraphicsEventHandlers(
    which=twlght.dev,
    prompt="Select Twilight",
    onMouseDown=twlOnMouseDown,
    onKeybd=onKeybd)
  ## Set up profile window
  X11(width=width,height=height)
  profile.dev <- dev.cur()
  profile.draw()
  setGraphicsEventHandlers(
    which=profile.dev,
    prompt="Light Profile",
    onMouseDown=prfOnMouseDown,
    onKeybd=onKeybd)
  ## Monitor for events
  tryCatch({
      getGraphicsEvent()
      dev.off(profile.dev)
      dev.off(twlght.dev)
      twilights
  }, finally=twilights)
}



##' Interactively edit crepuscular intervals
##'
##' Interactively edit the crepuscular intervals based on the light
##' profile.  A plot of the estimated sunrise and sunset intervals is
##' displayed, and the user can select the twilight to be edited with
##' a left mouse click.
##'
##' The light profile for the selected twilight is shown in a separate
##' window, and the selected segments of the light profile are
##' highlighted.  The corresponding light profiles from the preceeding
##' and following days are also shown for reference.
##'
##' The user may select a new candidate interval by clicking and
##' dragging with the left mouse button.  Individual points may be
##' selected or deselected with the right mouse button.
##'
##' Note however, no actual change to the selection is made until the
##' candidate edits are accepted depressing the 'a' key.
##'
##' Each twilight may be marked with the an integer 0 to 9 with the
##' numeric keys. By default each day is given the mark 0.
##'
##' In either window
##' \tabular{ll}{
##' 'q' \tab Quits, returning the dataframe of edited twilight segments \cr
##' 'a' \tab Accepts the candidate edit \cr
##' 'x' \tab Resets the selection \cr
##' 'p' \tab Toggles the display of individual points \cr
##' '+'/'-' \tab Zoom in or out \cr
##' 'Left arrow' \tab Jump to previous twilight \cr
##' 'Right arrow' \tab Jump to ext twilight \cr
##' '0'-'9' \tab Mark this twilight \cr
##' }
##'
##' @title Edit crepuscular segments
##' @param tagdata a datframe with columns \code{Date} and
##' \code{Light} that are the sequence of sample times (as POSIXct)
##' and light levels recorded by the tag.
##' @param twilights dataframe of twilight times as generated by
##' \code{\link{find.crepuscular}}.
##' @param offset the starting hour for the vertical axes.
##' @param extend the period (in hours) before and after twilight for
##' which the light profile should be plotted.
##' @param threshold the light threshold that defines twilight.
##' @param ymax the maximum light level to plot.
##' @param twilight.col the colors of the estimated sunrise and sunset intervals.
##' @param light.col the colors of the light profiles for the day
##' before, the selected twilight and the day after.
##' @param selected.col the colors of the selected light data when it
##' has accepted and when it is partially edited.
##' @param threshold.col the color of the threshold markers.
##' @param point.cex expansion factor for plot points.
##' @param width width of the interface windows.
##' @param height height of the interface windows.
##' @seealso \code{\link{twilight.editW}}
##' @return the dataframe of edited twilights, with columns
##' \item{\code{Twilight}}{edited times of twilight}
##' \item{\code{Rise}}{logical indicating sunrise}
##' \item{\code{Start}}{date of first observation in the crepuscular segment}
##' \item{\code{End}}{date of last observation in the crepuscular segment}
##' @export
crepuscular.editW <- function(tagdata,twilights,offset=0,extend=6,threshold=NULL,ymax=64,
                              twilight.col=c("dodgerblue","firebrick","grey80"),
                              light.col=c("#CCFFCC","black","#CCCCFF"),
                              threshold.col="red",selected.col=c("blue","red"),
                              point.cex=0.5,width=10,height=5) {

  ## Extract date and light
  date <- tagdata$Date
  light <- tagdata$Light
  ## Order twilights
  if(is.null(twilights$Marker)) twilights$Marker <- integer(nrow(twilights))
  twilights <- twilights[order(twilights$Twilight,twilights$Start),
                         c("Twilight","Rise","Start","End","Marker")]
  ## Extract date and hour of twilight
  day <- twilights$Twilight
  hour <- hour.offset(as.hour(twilights$Twilight),offset)

  ## Cached data subsets
  index <- 1
  indices <- as.numeric(factor(as.numeric(twilights$Twilight)))
  twl <- NULL
  marker <- 0
  dteA <- dteB <- dteC <- NULL
  lgtA <- lgtB <- lgtC <- NULL
  selected <- NULL
  start <- end <- 0
  changed <- FALSE
  show.obs <- FALSE

  ## Set cached values
  cache <- function(k) {
    index <<- k
    twl <<- twilights$Twilight[which(index==indices)[1]]
    marker <<- twilights$Marker[which(index==indices)[1]]
    changed <<- FALSE
    ## Get profiles
    keep <- (date >= twl-86400-3600*extend) & (date <= twl-86400+3600*extend)
    dteA <<- date[keep]
    lgtA <<- light[keep]
    keep <- (date >= twl - 3600*extend) & (date <= twl + 3600*extend)
    dteB <<- date[keep]
    lgtB <<- light[keep]
    keep <- (date >= twl+86400-3600*extend) & (date <= twl+86400+3600*extend)
    dteC <<- date[keep]
    lgtC <<- light[keep]

    selected <<- logical(length(dteB))
    for(i in which(index==indices))
      selected[dteB >= twilights$Start[i] & dteB <= twilights$End[i]] <<- TRUE
  }

  ## Select device
  devset <- function(dev) {
    if(dev.cur()!=dev) dev.set(dev)
  }
  ## Focus if possible
  focus <- if(exists("bringToTop",mode="function")) bringToTop else devset

  ## Draw the twilights window
  twlght.draw <- function() {
    plot(day,hour,type="n",
         xlab="Date",ylab="Hour",
         ylim=c(offset,offset+24))
    rise <- twilights[twilights$Rise,]
    tsimage.ribbon(.POSIXct(tapply(rise$Start,rise$Twilight,min),"GMT"),
                   .POSIXct(tapply(rise$End,rise$Twilight,max),"GMT"),
                   offset=offset,border=NA,col=twilight.col[1])
    set <- twilights[!twilights$Rise,]
    tsimage.ribbon(.POSIXct(tapply(set$Start,set$Twilight,min),"GMT"),
                   .POSIXct(tapply(set$End,set$Twilight,max),"GMT"),
                   offset=offset,border=NA,col=twilight.col[2])
    points(day[index],hour[index],pch=3)
  }


  ## Draw axes for light profiles
  profile.init <- function() {
    mlab <- if(marker>0) paste("Marker: ",marker) else ""
    plot(dteB,lgtB,xlab=mlab,ylab="Light",type="n",xaxt="n",main=as.character(twl))
    axis.POSIXct(1,x=dteB,format="%H:%M")
  }

  ## Draw light profiles
  profile.draw <- function() {
    ## Overlay light threshold
    if(!is.null(threshold))
      abline(h=threshold,col=threshold.col)
    ## Overlay the light profile for the selected and surrounding days
    lines(dteA+86400,lgtA,col=light.col[1])
    lines(dteC-86400,lgtC,col=light.col[3])
    lines(dteB,lgtB,col=light.col[2])
    if(show.obs) points(dteB,lgtB,col=light.col[2],pch=16,cex=point.cex)

    ## Show selection
    col <- if(!changed) selected.col[1] else selected.col[2]
    ## Hightlight selected segments
    x <- ifelse(selected,dteB,NA)
    y <- ifelse(selected,lgtB,NA)
    lines(x,y,col=col)
    if(show.obs) points(x,y,pch=16,cex=point.cex,col=col)
    ## Selection rectangles
    rx <- grconvertX(c(0,1),from="npc",to="user")
    ry <- grconvertY(c(1.01,1.03),from="npc",to="user")
    rect(rx[1],ry[1],rx[2],ry[2],border=NA,col="white",xpd=NA)
    if(any(selected)) {
      rect(dteB[diff(c(FALSE,selected))==1],ry[1],
           dteB[diff(c(selected,FALSE))==-1],ry[2],
           border=NA,col=col,xpd=NA)
    }
  }


  ## onMouseDown callback for twilights window.
  twlOnMouseDown <- function(buttons,x,y) {
    ## Determine selected profile.
    devset(twlght.dev)
    xs <- grconvertX(c(day,day,day),from="user",to="ndc")
    ys <- grconvertY(c(hour-24,hour,hour+24),from="user",to="ndc")
    k <- (which.min((x-xs)^2+(y-ys)^2)-1)%%length(day)+1
    ## Redraw
    cache(k)
    devset(twlght.dev)
    twlght.draw()
    devset(profile.dev)
    profile.init()
    profile.draw()
    focus(profile.dev)
    NULL
  }

  ## onKeybd callback for both windows
  onKeybd <- function(key) {
    ## q quits
    if(key=="q") return(-1)
    ## +/- : zoom time window around threshold crossing
    if(key=="+") {
      extend <<- max(extend-1,1)
      cache(index)
    }
    if(key=="-") {
      extend <<- min(extend+1,24)
      cache(index)
    }
    ## x : reset selection
    if(key=="x") {
      cache(index)
    }
    ## p : toggle display of points in the profile window
    if(key=="p") {
      show.obs <<- (show.obs==FALSE)
      #cache(index)
    }
    ## Left/Right : jump to neighbouring twilight
    if(key=="Left") {
      cache(max(index-1,1))
    }
    if(key=="Right") {
      cache(min(index+1,max(indices)))
    }
    ## a : accept current edit
    if(key=="a") {
      d <- split(twilights,twilights$Twilight)
      d[[index]] <- cbind(Twilight=d[[index]]$Twilight[1],
                          Rise=d[[index]]$Rise[1],
                          data.frame(Start=dteB[diff(c(FALSE,selected))==1],
                                     End=dteB[diff(c(selected,FALSE))==-1]),
                          Marker=d[[index]]$Marker[1])
      d <- do.call("rbind",d)
      d$Twilight <- .POSIXct(d$Twilight,"GMT")
      d$Start <- .POSIXct(d$Start,"GMT")
      d$End <- .POSIXct(d$End,"GMT")
      twilights <<- d
      indices <<- as.numeric(factor(as.numeric(twilights$Twilight)))
      changed <<- FALSE
    }
    if(key >= "0" && key <= "9") {
      marker <<- as.numeric(key)
      twilights$Marker[which(index==indices)] <<- marker
    }

    ## Redraw
    devset(twlght.dev)
    twlght.draw()
    devset(profile.dev)
    profile.init()
    profile.draw()
    NULL
  }

  ## onMouseDown callback for profile window
  prfOnMouseDown <- function(buttons,x,y) {
    ## Button 1 -> record location and do complete draw
    if(length(buttons) > 0 && buttons[1]==0) {
      changed <<- TRUE
      start <<- grconvertX(x,from="ndc",to="user")
      selected <<- logical(length(dteB))
      end <<- start
      profile.init()
    }
    ## Button 2 -> toggle selected points
    if(length(buttons) > 0 && buttons[1]==2) {
      changed <<- TRUE
      xs <- grconvertX(dteB,from="user",to="ndc")
      ys <- grconvertY(lgtB,from="user",to="ndc")
      k <- which.min((x-xs)^2+(y-ys)^2)
      selected[k] <<- (selected[k]==FALSE)
    }
    profile.draw()
    NULL
  }

  ## onMouseMove callback for profile window
  prfOnMouseMove <- function(buttons,x,y) {
    ## Button 1 drag to select crepuscular period
    if(length(buttons) > 0 && buttons[1]==0) {
      end <<- grconvertX(x,from="ndc",to="user")
      sel <- (dteB >= min(start,end) & dteB <= max(start,end))
      if(any(sel!=selected)) {
        selected <<- sel
        profile.draw()
      }
    }
    NULL
  }

  ## Set up twilights window
  index <- 1
  cache(index)
  X11(width=width,height=height)
  twlght.draw()
  twlght.dev <- dev.cur()
  setGraphicsEventHandlers(
    which=twlght.dev,
    prompt="Select Twilight",
    onMouseDown=twlOnMouseDown,
    onKeybd=onKeybd)
  ## Set up profile window
  X11(width=width,height=height)
  profile.dev <- dev.cur()
  profile.init()
  profile.draw()
  setGraphicsEventHandlers(
    which=profile.dev,
    prompt="Light Profile",
    onMouseDown=prfOnMouseDown,
    onMouseMove=prfOnMouseMove,
    onKeybd=onKeybd)
  focus(twlght.dev)
  ## Monitor for events
  tryCatch({
      getGraphicsEvent()
      dev.off(profile.dev)
      dev.off(twlght.dev)
      twilights
  }, finally=twilights)
}



